[versions]
agp = "8.5.0"
appcompat = "1.7.0"
circleimageview = "3.1.0"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
sdpAndroid = "1.1.1"
sspAndroid = "1.1.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

